defmodule ShopWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :shop

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_shop_key",
    signing_salt: "vv1XysRE",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: {__MODULE__, :session_options, []}]],
    longpoll: [connect_info: [session: {__MODULE__, :session_options, []}]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug :public_font_cors

  plug Plug.Static,
    at: "/",
    from: :shop,
    gzip: not code_reloading?,
    only: ShopWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :shop
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug ShopWeb.Plugs.TrustedProxy
  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug :load_session

  @doc false
  def session_options do
    if Application.get_env(:shop, :exploration) do
      Keyword.merge(@session_options,
        key: "__Host-shop_exploration",
        secure: true,
        same_site: "None",
        extra: "Partitioned"
      )
    else
      @session_options
    end
  end

  defp load_session(conn, _), do: Plug.Session.call(conn, Plug.Session.init(session_options()))
  plug ShopWeb.Router
  # Sandboxed previews have an opaque origin. Only successful public font
  # responses (including cache revalidation) permit credential-free CORS.
  defp public_font_cors(
         %Plug.Conn{path_info: ["assets", "published", "fonts", filename]} = conn,
         _opts
       ) do
    if Path.extname(filename) == ".woff2" do
      register_before_send(conn, &allow_public_font/1)
    else
      conn
    end
  end

  defp public_font_cors(conn, _opts), do: conn

  defp allow_public_font(%Plug.Conn{status: status} = conn) when status in [200, 206, 304] do
    put_resp_header(conn, "access-control-allow-origin", "*")
  end

  defp allow_public_font(conn), do: conn
end
